[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:caddy]
command=caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
priority=10
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:php-fpm]
command=php-fpm8.4 --nodaemonize
priority=10
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:icecast2]
command=icecast2 -c /etc/icecast2/icecast.xml
user=birdnet
priority=20
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:birdnet_analysis]
command=/opt/birdnet/venv/bin/python3 /opt/birdnet/scripts/birdnet_analysis.py
directory=/opt/birdnet/scripts
environment=BIRDNET_CONFIG="/opt/birdnet/birdnet.conf"
user=birdnet
priority=30
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

[program:chart_viewer]
command=/opt/birdnet/venv/bin/python3 /opt/birdnet/scripts/daily_plot.py --daemon --sleep 2
directory=/opt/birdnet/scripts
environment=BIRDNET_CONFIG="/opt/birdnet/birdnet.conf"
user=birdnet
priority=40
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:spectrogram_viewer]
command=/opt/birdnet/scripts/spectrogram.sh
environment=BIRDNET_CONFIG="/opt/birdnet/birdnet.conf"
user=birdnet
priority=40
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

; Only works if RTSP_STREAM is configured or an audio device is passed through
[program:birdnet_recording]
command=/opt/birdnet/scripts/birdnet_recording.sh
user=birdnet
priority=25
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

; Only works if RTSP_STREAM is configured or an audio device is available
[program:livestream]
command=/opt/birdnet/scripts/livestream.sh
user=birdnet
priority=50
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:streamlit]
command=/opt/birdnet/venv/bin/streamlit run /opt/birdnet/scripts/plotly_streamlit.py --browser.gatherUsageStats false --server.address 127.0.0.1 --server.baseUrlPath /stats
environment=BIRDNET_CONFIG="/opt/birdnet/birdnet.conf"
user=birdnet
priority=50
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
